import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f6f7fb',
  },
  backBtn: {
    marginLeft: 14, // trung bình giữa 12 và 16
    marginBottom: 0,
    alignSelf: 'flex-start',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
    marginBottom: 8, // trung bình giữa 0, 12
    marginTop: 15, // trung bình giữa 10, 20
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    marginHorizontal: 16,
    marginTop: 0, // chỉ VerifyUser dùng marginTop: 20, có thể truyền prop ngoài
    marginBottom: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: '#222',
    paddingVertical: 4,
  },
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
    minHeight: 95,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    backgroundColor: '#eee',
  },
  infoCol: {
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
  },
  name: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 2,
  },
  email: {
    fontSize: 13,
    color: '#666',
    marginBottom: 2,
    fontStyle: 'italic',
  },
  mssv: {
    fontSize: 13,
    color: '#888',
    marginBottom: 2,
    fontWeight: 'bold',
  },
  time: {
    fontSize: 13,
    color: '#888',
    marginBottom: 2,
  },
  verifyBtn: {
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 80,
  },
  verifyText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  setBtn: {
    backgroundColor: '#3b82f6',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 90,
  },
  setText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 14,
  },
  deleteUserBtnUser: {
    backgroundColor: '#ef4444',
    justifyContent: 'center',
    alignItems: 'center',
    width: 70,
    height: '96%',
    borderRadius: 14,
    marginVertical: 0,
    marginRight: 10,
    marginTop: 10,
    marginBottom: 11,
    marginLeft: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 2,
    elevation: 2,
  },
  deleteTextUser: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 15,
  },
  roleModalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  roleModalBox: {
    width: 280,
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  roleModalTitle: {
    fontWeight: 'bold',
    fontSize: 17,
    marginBottom: 10,
    textAlign: 'center',
  },
  roleOption: {
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#f3f4f6',
    marginBottom: 6,
    alignItems: 'center',
    width: '100%',
  },
  roleOptionSelected: {
    backgroundColor: '#2563eb',
  },
  roleOptionText: {
    color: '#222',
    fontWeight: 'bold',
    fontSize: 15,
  },
  roleOptionTextSelected: {
    color: '#fff',
  },
  roleModalCloseBtn: {
    marginTop: 8,
    alignItems: 'center',
  },
  roleModalCloseText: {
    color: '#2563eb',
    fontWeight: 'bold',
    fontSize: 15,
  },
});

export default styles; 